python train.py \
 --game connectfour \
 --n-in-row 4 \
 --board-height 6 \
 --board-width 7 \
 --n-filter 32 \
 --batch-size 1024 \
 --save-path ${PWD}/connectfour_training_model/ \
 --load-path ${PWD}/connectfour_training_model/201806220927_connectfour_n_in_row_4_board_6_7_res_blocks_5_filters_32 \
 --epochs 200 \
 --learning-rate 1e-2 \
 --learning-rate-f 1e-4 \
 --train-on-game-data-only \
 --train-on-last-n-sets 10000
